project:
  type: website

brand: _brand.yml

website:
  title: "DistNet — töö käik"
  navbar:
    left:
      - href: index.qmd
        text: Kodu

format:
  html:
    toc: true
    theme: litera
    metadata:
      robots: noindex